os: linux
language: node_js
node_js:
  - 8.12
dist: trusty

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    - build

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: Test
      script: yarn test
    - stage: Build
      script: yarn build
    - stage: Deploy
      script: echo 'play.bpdash.com' > ./build/CNAME
      deploy:
        provider: pages
        skip_cleanup: true,
        local_dir: ./build
        token: $GITHUB_TOKEN

notifications:
  email: false
